import { IExercise } from "../context/ExerciseContext";

export const e: IExercise[] = [
   {
      bodyPart: "waist",
      equipment: "body weight",
      gifUrl: "https://v2.exercisedb.io/image/icxIix2RIZ7ZQ6",
      id: "0006",
      name: "alternate heel touchers",
      target: "abs",
      secondaryMuscles: ["obliques"],
      instructions: [
         "Lie flat on your back with your knees bent and feet flat on the ground.",
         "Extend your arms straight out to the sides, parallel to the ground.",
         "Engaging your abs, lift your shoulders off the ground and reach your right hand towards your right heel.",
         "Return to the starting position and repeat on the left side, reaching your left hand towards your left heel.",
         "Continue alternating sides for the desired number of repetitions.",
      ],
   },
   {
      bodyPart: "back",
      equipment: "cable",
      gifUrl: "https://v2.exercisedb.io/image/RVJr87zJPkAGA7",
      id: "0007",
      name: "alternate lateral pulldown",
      target: "lats",
      secondaryMuscles: ["biceps", "rhomboids"],
      instructions: [
         "Sit on the cable machine with your back straight and feet flat on the ground.",
         "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
         "Lean back slightly and pull the handles towards your chest, squeezing your shoulder blades together.",
         "Pause for a moment at the peak of the movement, then slowly release the handles back to the starting position.",
         "Repeat for the desired number of repetitions.",
      ],
   },
   {
      bodyPart: "chest",
      equipment: "leverage machine",
      gifUrl: "https://v2.exercisedb.io/image/Ctn79xEhpDondN",
      id: "0009",
      name: "assisted chest dip (kneeling)",
      target: "pectorals",
      secondaryMuscles: ["triceps", "shoulders"],
      instructions: [
         "Adjust the machine to your desired height and secure your knees on the pad.",
         "Grasp the handles with your palms facing down and your arms fully extended.",
         "Lower your body by bending your elbows until your upper arms are parallel to the floor.",
         "Pause for a moment, then push yourself back up to the starting position.",
         "Repeat for the desired number of repetitions.",
      ],
   },
   {
      bodyPart: "waist",
      equipment: "assisted",
      gifUrl: "https://v2.exercisedb.io/image/PBIER1jdszfaJQ",
      id: "0010",
      name: "assisted hanging knee raise with throw down",
      target: "abs",
      secondaryMuscles: ["hip flexors", "lower back"],
      instructions: [
         "Hang from a pull-up bar with your arms fully extended and your palms facing away from you.",
         "Engage your core and lift your knees towards your chest, keeping your legs together.",
         "Once your knees are at chest level, explosively throw your legs down towards the ground, extending them fully.",
         "Allow your legs to swing back up and repeat the movement for the desired number of repetitions.",
      ],
   },
   {
      bodyPart: "waist",
      equipment: "assisted",
      gifUrl: "https://v2.exercisedb.io/image/xmRcotPLMGCK7s",
      id: "0011",
      name: "assisted hanging knee raise",
      target: "abs",
      secondaryMuscles: ["hip flexors"],
      instructions: [
         "Hang from a pull-up bar with your arms fully extended and your palms facing away from you.",
         "Engage your core muscles and lift your knees towards your chest, bending at the hips and knees.",
         "Pause for a moment at the top of the movement, squeezing your abs.",
         "Slowly lower your legs back down to the starting position.",
         "Repeat for the desired number of repetitions.",
      ],
   },
   {
      bodyPart: "waist",
      equipment: "assisted",
      gifUrl: "https://v2.exercisedb.io/image/YXBRjp96Qf63La",
      id: "0012",
      name: "assisted lying leg raise with lateral throw down",
      target: "abs",
      secondaryMuscles: ["hip flexors", "obliques"],
      instructions: [
         "Lie flat on your back with your legs extended and your arms by your sides.",
         "Place your hands under your glutes for support.",
         "Engage your abs and lift your legs off the ground, keeping them straight.",
         "While keeping your legs together, lower them to one side until they are a few inches above the ground.",
         "Pause for a moment, then lift your legs back to the starting position.",
         "Repeat the movement to the other side.",
         "Continue alternating sides for the desired number of repetitions.",
      ],
   },
   {
      bodyPart: "waist",
      equipment: "assisted",
      gifUrl: "https://v2.exercisedb.io/image/YhiMMw8YAV1lAa",
      id: "0013",
      name: "assisted lying leg raise with throw down",
      target: "abs",
      secondaryMuscles: ["hip flexors", "quadriceps"],
      instructions: [
         "Lie flat on your back with your legs extended and your arms by your sides.",
         "Place your hands under your glutes for support.",
         "Engage your core and lift your legs off the ground, keeping them straight.",
         "Raise your legs until they are perpendicular to the ground.",
         "Lower your legs back down to the starting position.",
         "Simultaneously, throw your legs down towards the ground, keeping them straight.",
         "Raise your legs back up to the starting position.",
         "Repeat for the desired number of repetitions.",
      ],
   },
   {
      bodyPart: "waist",
      equipment: "medicine ball",
      gifUrl: "https://v2.exercisedb.io/image/Jknwm2bSJWG--1",
      id: "0014",
      name: "assisted motion russian twist",
      target: "abs",
      secondaryMuscles: ["obliques", "lower back"],
      instructions: [
         "Sit on the ground with your knees bent and feet flat on the floor.",
         "Hold the medicine ball with both hands in front of your chest.",
         "Lean back slightly, engaging your abs and keeping your back straight.",
         "Slowly twist your torso to the right, bringing the medicine ball towards the right side of your body.",
         "Pause for a moment, then twist your torso to the left, bringing the medicine ball towards the left side of your body.",
         "Continue alternating sides for the desired number of repetitions.",
      ],
   },
   {
      bodyPart: "back",
      equipment: "leverage machine",
      gifUrl: "https://v2.exercisedb.io/image/Y7jXbAlVlAzwYE",
      id: "0015",
      name: "assisted parallel close grip pull-up",
      target: "lats",
      secondaryMuscles: ["biceps", "forearms"],
      instructions: [
         "Adjust the machine to your desired weight and height.",
         "Place your hands on the parallel bars with a close grip, palms facing each other.",
         "Hang from the bars with your arms fully extended and your feet off the ground.",
         "Engage your back muscles and pull your body up towards the bars, keeping your elbows close to your body.",
         "Continue pulling until your chin is above the bars.",
         "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
         "Repeat for the desired number of repetitions.",
      ],
   },
   {
      bodyPart: "upper legs",
      equipment: "assisted",
      gifUrl: "https://v2.exercisedb.io/image/takhjQLBPH863u",
      id: "0016",
      name: "assisted prone hamstring",
      target: "hamstrings",
      secondaryMuscles: ["glutes", "lower back"],
      instructions: [
         "Lie face down on a mat or bench with your legs fully extended.",
         "Have a partner or use a resistance band to secure your ankles.",
         "Engage your hamstrings and lift your legs towards your glutes, keeping your knees straight.",
         "Pause for a moment at the top, then slowly lower your legs back down to the starting position.",
         "Repeat for the desired number of repetitions.",
      ],
   },
];
